sudo: required

services:
  - docker

before_install:
- docker pull partouf2/docker-obs-studio
- docker run partouf2/docker-obs-studio /bin/sh -c "cd /home && git clone https://github.com/partouf/Crosscables.git && cd Crosscables/libGroundfloor && sh build.sh && cd /home && git clone https://github.com/partouf/OBSInfoWriter.git && cd OBSInfoWriter && git checkout $TRAVIS_BRANCH && make -f Makefile.linux"
