sudo: required
language: cpp
services:
- docker
before_install:
- docker pull partouf2/docker-obs-studio
- docker run -v "$TRAVIS_BUILD_DIR:/home/OBSInfoWriter" partouf2/docker-obs-studio /bin/sh -c "cd /home && git clone https://github.com/partouf/Crosscables.git
  && cd Crosscables/libGroundfloor && sh build.sh && cd /home
  && cd OBSInfoWriter && make -f Makefile.linux"
script:
- sudo chmod -Rf 0777 $TRAVIS_BUILD_DIR
- echo OK
deploy:
  provider: releases
  api_key:
    secure: FDC2iP97l5uZUnmEKQix2wnPQ/3TGX61smVbdjauDCzeYezRwjgveE02UPnqZg7+lpZD2er1x44oYbBxrAjFMYmaJi7wIKh0EO/kym8bf1FM1dwiD/+asrK23yjzPZGKW5aGCPqJuHZUOH9lWIAd3xjSvrrOwCaWFdBgIoSNu0imwRy++WxT45M4XsXCVRl7hwHz3r3EnfnA4thl8qTqxjxU82TS83zs6ecj9tOuRk8/G/WEKYGJc80VTKRoRyy6L2f3FNdKSg+rlf6gBB7EcSjLZ49lDHyrldIFVPt/qoeUfXzjwZ0tyYmmA4hX2g0HAFTTJ178gX6DpsdnJ42HzsxIBJeIiKw/ZKYRl2PKovKs6VDEyxFrufnrlk84SCY40wJB1bJNKeNeGwaSw0iu9jiNAd57ReKcwKieIqPLgstB6ICc+Vghjv/0G92iPHXUMO5J925v/jDUYkpTJ4mxQpbqkKHfnpGtz0wQQVyv3wzctEM07GdPufvjCrj2ozNcUZd8AgFthfnd3xObJ5n9ZSmYNxVpS25C8SaVyr+ablkr9+omUH1upaVr8x09b6JZnTJydSMkn8dc9/BEWCycz0J4K8F3y93r+n2N3XIm5UFzYxH3djHRiCnJBaNyPCEfKbmBshK4eRyf3PaMzzS3i0n99T/b05SGkixNtXqQhwM=
  file: "$TRAVIS_BUILD_DIR/libOBSInfoWriter.so"
  skip_cleanup: true
  on:
    repo: partouf/OBSInfoWriter
    tags: true
